apiVersion: v1
kind: Pod
metadata:
  name: k8s-monitoring-expose
spec:
  serviceAccountName: k8s-monitoring-expose
  containers:
    - name: k8s-monitoring-expose
      image: xz446/k8s-monitoring-expose:0.0.8