---

# Initialize control plane for each cluster master
- name: Control plane initialization
  hosts: cluster4_master
  become: yes
  become_user: root
  gather_facts: no

  vars:
    home_path: /home/jack
    username: jack
    calico_version: 3.27.2

  tasks:
    #- name: Add the Kubernetes apt repository
    #  ansible.builtin.apt_repository:
    #    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    #    state: present
#
    #- name: Add GPG key for Kubernetes repository
    #  ansible.builtin.apt_key:
    #    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    #    state: present

    - name: Initialize the Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///var/run/crio/crio.sock
      register: init_result
      failed_when: init_result.rc != 0

    - name: export KUBECONFIG
      shell: export KUBECONFIG=/etc/kubernetes/admin.conf

    - name: Deploy Calico network
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file for cluster4_master
      local_action:
        module: copy
        content: "{{ join_command.stdout }}"
        dest: "/tmp/kubernetes_join_command_cluster4"
      when: inventory_hostname in groups['cluster4_master']

# Join worker nodes to their respective clusters
- name: Join worker nodes
  hosts: cluster4_worker
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Copy join command to workers of cluster4
      copy:
        src: "/tmp/kubernetes_join_command_cluster4"
        dest: "/tmp/kubernetes_join_command"
        mode: '0777'
      when: inventory_hostname in groups['cluster4_worker']

    - name: Execute the join command on worker nodes
      shell: sh /tmp/kubernetes_join_command
      when: inventory_hostname in groups['cluster4_worker']
