---

# update all ubuntu nodes
- name: get update for all ubnutu hosts, then turn off swap for all
  hosts: cluster4
  become: yes
  gather_facts: yes

  tasks:

    - name: update all ubuntu hosts
      apt:
        update_cache: yes

    - name: temporarily disable swap filw
      shell: |
        sudo swapoff -a

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: test if swap is off
      shell: sudo swapon --show

# enable ipv4_forwarding on kube nodes
- name: enable ipv4 forward
  hosts: cluster4
  become: yes
  gather_facts: no

  tasks:

    - name: enable ipv4 forward
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        sudo modprobe overlay
        sudo modprobe br_netfilter  
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF
        sudo sysctl --system
        lsmod | grep br_netfilter && lsmod | grep overlay
        sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward

# update RTC since some nodes might be off
- name: update RTC
  hosts: cluster4
  become: yes
  gather_facts: no

  tasks:
    - name: update RTC
      shell: |
        sudo systemctl unmask systemd-timesyncd
        sudo apt install systemd-timesyncd
        sudo systemctl enable systemd-timesyncd.service
        sudo systemctl start systemd-timesyncd.service
