---

# Test metric server by fetching master node utilization
- name: test metric server deployment
  hosts: masters
  become: yes
  gather_facts: no

  tasks:
    - name: test metric server
      become: yes
      shell: |
        kubectl top nodes | grep "master"
      register: kubectl

    - ansible.builtin.debug:
        msg: "{{ kubectl.stdout_lines }}"