---

- name: Install Kubernetes modules
  hosts: cluster4
  become: yes
  become_user: root
  gather_facts: no

  vars:
    versions: 1.28.2-00

  tasks:

    - name: Update apt cache after adding new repository
      ansible.builtin.apt:
        update_cache: yes

    - name: Install specific versions of Kubernetes packages
      ansible.builtin.apt:
        name:
          - kubelet={{ versions }}
          - kubeadm={{ versions }}
          - kubectl={{ versions }}
        state: present
