---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-monitoring-expose
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-monitoring-expose
rules:
# allow the service account to do what-ever
- apiGroups: ["*"]
  resources: ["pods", "nodes", "svc", "deployments"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-monitoring-expose
subjects:
- kind: ServiceAccount
  name: k8s-monitoring-expose
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-monitoring-expose
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-monitoring-expose-service
  namespace: kube-system
  labels:
    app: k8s-monitoring-expose
spec:
  selector:
    app: k8s-monitoring-expose
  type: NodePort
  ports:
    # update to receive peer updates
    - name: update
      port: 8080
      targetPort: 8080
      nodePort: 30001
    # migration to receive decision, such as "migration"
    - name: migration
      port: 8081
      targetPort: 8081
      nodePort: 30002
    # iperf to provide server end for iperf3 bandwidth calculation
    - name: iperf
      port: 5201
      targetPort: 5201
      nodePort: 30003
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-monitoring-expose-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitoring-expose
  template:
    metadata:
      labels:
        app: k8s-monitoring-expose
    spec:
      serviceAccountName: k8s-monitoring-expose
      containers:
        - name: k8s-monitoring-expose
          image: xz446/k8s-monitoring-expose:0.0.28
          imagePullPolicy: Always
          ports:
            # http1 to receive peer updates
            - name: update
              containerPort: 8080
            # http2 to receive decision, such as "migration"
            - name: migration
              containerPort: 8081
            # port for iperf3 server
            - name: iperf
              containerPort: 5201
          env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP