apiVersion: v1
kind: Service
metadata:
  name: uvicorn-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: uvicorn-app
  ports:
    - name: test
      port: 8080
      targetPort: 8080
      nodePort: 30004

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: uvicorn-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uvicorn-app
  template:
    metadata:
      labels:
        app: uvicorn-app
    spec:
      containers:
      - name: uvicorn-container
        image: xz446/hello-uvicorn:0.0.3
        ports:
        - name: test
          containerPort: 8080
