---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mono-monitor
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts"]
  verbs: ["create", "delete", "get", "list", "top"]
- apiGroups: ["*"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mono-monitor
subjects:
- kind: ServiceAccount
  name: mono-monitor
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: mono-monitor  
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mono-monitor
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete"]
- apiGroups: ["*"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mono-monitor-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mono-monitor
  namespace: kube-system
roleRef:
  kind: Role
  name: mono-monitor
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system


---
apiVersion: v1
kind: Service
metadata:
  name: mono-monitor-service
  namespace: kube-system
  labels:
    app: mono-monitor
spec:
  selector:
    app: mono-monitor
  type: NodePort
  ports:
    # update to receive peer updates
    - name: update
      port: 8080
      targetPort: 8080
      nodePort: 30001
    # migration to receive decision, such as "migration"
    - name: migration
      port: 8081
      targetPort: 8081
      nodePort: 30002
    # iperf to provide server end for iperf3 bandwidth calculation
    - name: iperf
      port: 5201
      targetPort: 5201
      nodePort: 30003
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mono-monitor
  namespace: kube-system

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mono-monitor-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mono-monitor
  template:
    metadata:
      labels:
        app: mono-monitor
    spec:
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
      serviceAccountName: mono-monitor
      containers:
        - name: mono-monitor
          image: xz446/mono-monitor:0.3
          imagePullPolicy: Always
          ports:
            # http1 to receive peer updates
            - name: update
              containerPort: 8080
            # http2 to receive decision, such as "migration"
            - name: migration
              containerPort: 8081
            # port for iperf3 server
            - name: iperf
              containerPort: 5201
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
