apiVerison: apps/v1
kind: Deployment
metadata:
  name: k8s-monitoring-expose-deployment
  labels:
    app: k8s-monitoring-expose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitoring-expose
  template:
    metadata:
      labels:
        app: k8s-monitoring-expose
    spec:
      containers:
        - name: k8s-monitoring-expose
          image: xz446/k8s-monitoring-expose:0.0.1
          ports:
            - containerPort: 80