---
- name: Set up root user password on selected Ubuntu hosts
  hosts: selected_ubuntu_hosts
  become: yes
  gather_facts: no

  vars:
    root_password: "{{ '  - name: Add GPG key for Kubernetes repository
      ansible.builtin.apt_key:' }}"

  tasks:
    - name: Set root user password
      ansible.builtin.user:
        name: root
        password: "{{ root_password }}"
        update_password: always

