---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-monitoring-expose
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: k8s-monitoring-expose
roleRef:
  kind: Role
  name: k8s-monitoring-expose
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-monitoring-expose
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - delete
      - top
      - apply

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-monitoring-expose
  namespace: kube-system

---
# pod deployment
apiVersion: v1
kind: Pod
metadata:
  name: k8s-monitoring-expose
  namespace: kube-system
spec:
  serviceAccountName: k8s-monitoring-expose
  containers:
    - name: k8s-monitoring-expose
      image: xz446/k8s-monitoring-expose:0.0.10