apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-monitoring-expose
subjects:
  - kind: ServiceAccount
    name: k8s-monitoring-expose
roleRef:
  kind: Role
  name: k8s-monitoring-expose
  apiGroup: rbac.authorization.k8s.io