kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-monitoring-expose-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitoring-expose
  template:
    metadata:
      labels:
        app: k8s-monitoring-expose
    spec:
      containers:
        - name: k8s-monitoring-expose
          image: xz446/k8s-monitoring-expose:0.0.10
          imagePullPolicy: Always
          ports:
            - containerPort: 80
