---

# Metrics server deployment

# added into crio-deployment script

- name: Metrics server deployment
  hosts: cluster3_master
  become: yes
  gather_facts: no

  tasks:
    - name: Copy metrics server deployment
      become: yes
      ansible.builtin.copy:
        src: ../k8s_deployments/metrics_deployment.yaml
        dest: ./metrics_deployment.yaml
        mode: 0777

    - name: Run metrics server deployment
      become: yes
      ansible.builtin.shell:
        cmd: kubectl apply -f metrics_deployment.yaml

# Test metric server by fetching master node utilization
- name: test metric server deployment
  hosts: cluster3_master
  become: yes
  gather_facts: no

  tasks:
    - name: test metric server
      become: yes
      shell: |
        kubectl top nodes | grep master
      register: kubectl

    - ansible.builtin.debug:
        msg: "{{ kubectl.stdout_lines }}"

